
import { Inter } from 'next/font/google';
// import 'swiper/swiper.min.css';
// import './globals.css'
import Head from 'next/head';
import Header from './components/Header';
import HeroBanner from './components/HeroBanner';
import Footer from './components/Footer';
import { seoData } from './helper/herobanner/seo';
import { usePathname } from 'next/navigation';
// import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const pathname = usePathname();
  
  function getSeoData(){

    const metaData = seoData.find(page => page.pageUrl === pathname);

    console.log(metaData, 'metaData');

    return metaData
    
  }


  const metaData = getSeoData();

  return (
    <html lang="en">
      <Head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <meta name='titile' content={metaData?.metaTitle}/>
        <meta name='keywords' content={metaData?.metaKeywords}/>
        <meta name='description' content={metaData?.metaDescription}/>
        <title>{metaData?.metaTitle}</title>
      </Head>


      <body className={inter.className}>
        <Header />
        <HeroBanner />
        {children}
        <Footer />
      </body>
    </html>
  );
}