
import { Inter } from 'next/font/google';
// import 'swiper/swiper.min.css';
// import './globals.css'
import Head from 'next/head';
// import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      </Head>

      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
